action: inspect
host:
  path: config/definitions/host/
  filters: 
    local:true
php:
  dir: php-builds/**/*.*
  filters:
    platform: windows
    compiler: vc9
middleware:
  definition-files: config/definitions/middleware/**/*.rb
