host:
  path: config/definitions/host
  filters: 
    type: local
php:
  dir: php-builds/*
  filters:
    platform: windows
    compiler: VC9
middleware:
  filters:
    interface: cli
phpt: phpt/**/*.phpt