host:
  path: config/definitions/host/
#  filters: 
#    type: local
contexts:
  path: config/definitions/context/
php:
  dir: php-builds/*
  filters:
    platform: windows
    compiler: VC9
middleware:
#  filters:
#    interface: cli
phpt: 